name: Semgrep run
on:
  pull_request:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Run semgrep
        env:
          # Connect to Semgrep Cloud Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep Cloud Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_PR_ID: ${{ github.event.client_payload.number }}

        run: |
          echo "Running Semgrep"
          semgrep ci --verbose
